### ISSUE TITLE
linking Resources

### ISSUE THREAD

**Issue by Gabrax** [electronstudio/jaylib-example-project#2]
in build.gradle copying resources didnt work properly when running distZip.

Wanted to create pull request, but permission denied. Below is the code that i suggest to change

```
distributions {
    main {
        contents {
            into('bin/resources'){
                from 'resources'
            }
        }
    }
}
```

**Comment by electronstudio** [comment]
I'm unable to reproduce this problem.  Resources get copied into resources directory fine for me.

What you probably want to do is read the APP_HOME environment variable and prefix your resource file paths with that directory when you load them.

**Comment by electronstudio** [comment]
Seems APP_HOME isn't exported by the launch script (unless you modify it to `export APP_HOME` so I'm not sure what the nicest way of doing this is.  Packaging java applications is quite a complicated topic and `distZip` doesn't give you a fully portable application anyway because you still need a JVM to run it.

**Comment by electronstudio** [comment]
The current `distZip` works but has the assumptions
1. System has a JVM already installed
2. The current directory when the launch script is run is the `jaylib-example-project-1.0-SNAPSHOT` directory.

**Comment by Gabrax** [comment]
Im not a java expert, so i dont know how to optimize distribution task to generate a exe file with dependencies. For now i only know people, use third party applications to make jar a exe file.

In distZip i found the problem, when resources werent in bin folder, if u dont have this problem maybe my computer is somehow broken. 

Also thank you for replying, you can close the issue if you think there is no problem

**Comment by electronstudio** [comment]
There’s jpackage, graal native image and third party jdeploy is pretty good. 

The issue with distZip is that it doesn’t set the current directory when the app launches. So apparently on your machine the current directory is set to the bin folder, so if you try to load a local path ‘resources/x’ it tries to load ‘bin/resources/x’. You could try ‘../resources/x’.
